const data = {
    products: [
        {
            _id:'1',
            name:'Dress',
            category:'Top',
            image:'/images/p1.jpg',
            price:250,
            countInStock: 10,
            brand:'JB',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Full Dress',
            category:'Top',
            image:'/images/p2.jpg',
            price:450,
            countInStock: 20,
            brand:'JB',
            rating:4,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Mens Wear',
            category:'Top',
            image:'/images/p3.jpg',
            price:620,
            countInStock: 0,
            brand:'HereNow',
            rating:3,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Shirt',
            category:'Top',
            image:'/images/p4.jpg',
            price:1200,
            countInStock: 15,
            brand:'HereNow',
            rating:3.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Blazer',
            category:'Top',
            image:'/images/p5.jpg',
            price:500,
            countInStock: 1,
            brand:'Amazon',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Shirt',
            category:'Top',
            image:'/images/p6.jpg',
            price:350,
            countInStock: 0,
            brand:'Amazon',
            rating:4,
            numReviews:10,
            description:'high quality product',
        },

    ],
};
export default data;